from setuptools import setup, find_packages

setup(
    name="collatz",               # The package name
    version="0.1",                   # Initial version
    packages=find_packages(),        # Automatically find packages in the directory
    install_requires=[
        "networkx>=3.4.2",
        "matplotlib>=3.10.1"
    ],
    description="Package for exploring odd number digraph generated by collatz process.",
    author="Ben Herzog",
)
